// Deterministic "what to do next" engine for Corvus's guidance panel in
// CaseDetailModal.tsx — same discipline as pre-filing-check.ts/
// executive-summary.ts: every fact here comes from a real field already on
// the case/property, or from county-protest-info.ts's real, hand-verified
// per-county dataset. Never an AI call, never an invented fact — a stage
// and a next-step list are just a straightforward function of state this
// app already has. Corvus's own copy/branding narrates this, but nothing
// in the output is generated by a model.
import type { PropertyRecord } from "./properties";
import type { ProtestRecord, ProtestStatus } from "./protests";
import type { CountyProtestInfo } from "./county-protest-info";

export type CaseStage =
  "prepare_file" | "filed" | "informal_review" | "hearing" | "decision" | "escalation" | "resolved";

// Exhaustive by construction — TypeScript errors if a future ProtestStatus
// value is added here without a stage assigned, so this can never silently
// leave a real case with no guidance at all.
const STAGE_BY_STATUS: Record<ProtestStatus, CaseStage> = {
  requested: "prepare_file",
  filed: "filed",
  under_review: "filed",
  offer_received: "informal_review",
  hearing_scheduled: "hearing",
  decision_received: "decision",
  appealing: "escalation",
  arbitrating: "escalation",
  resolved: "resolved",
};

const STAGE_LABEL: Record<CaseStage, string> = {
  prepare_file: "Prepare & File",
  filed: "Filed — Under Review",
  informal_review: "Informal Review",
  hearing: "Formal Hearing",
  decision: "Decision",
  escalation: "Escalation",
  resolved: "Resolved",
};

export type GuidanceStep = {
  label: string;
  detail: string;
  // Matches an element id already rendered by an existing section below
  // (Documents, CaseProgress's own forms) or a real external URL (a
  // county's own filing portal) — a step always points at real,
  // already-working UI, never a new surface.
  action?: { label: string; anchor: string };
};

export type CaseGuidance = {
  stage: CaseStage;
  stageLabel: string;
  summary: string;
  nextSteps: GuidanceStep[];
  countyInfo: CountyProtestInfo | null;
};

function formatDate(iso: string): string {
  // Same local-midnight fix as pre-filing-check.ts's deadline row — a
  // date-only string parsed as-is reads as UTC midnight, rolling the
  // displayed date back a day for anyone west of UTC.
  return new Date(`${iso}T00:00:00`).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

function formatCurrency(value: number): string {
  return value.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });
}

function isFutureDate(iso: string): boolean {
  return new Date(`${iso}T23:59:59`).getTime() >= Date.now();
}

// Real count of "Protest Evidence"-tagged documents uploaded for this
// property (see getProtestEvidenceDocuments in documents.ts) — evidence
// now uploads exclusively through Module 8 (ai-report.tsx), a flat
// document list rather than a per-item checklist, so this can only ever
// honestly nudge "you haven't uploaded anything yet," not "you're missing
// item N of M." No action/anchor: Module 8 lives on a different route
// (with its own real-property intake-state setup), which this pure data
// function has no way to trigger — the "Upload Evidence" button that does
// that lives in CaseDetailModal.tsx itself.
function evidenceSteps(evidenceDocumentCount: number | undefined): GuidanceStep[] {
  if (evidenceDocumentCount == null || evidenceDocumentCount > 0) return [];
  return [
    {
      label: "Upload evidence to support your case",
      detail:
        "You haven't uploaded any evidence yet. Use the Upload Evidence button to add documents in Module 8 — stronger evidence supports a stronger case.",
    },
  ];
}

function filingMethodStep(countyInfo: CountyProtestInfo | null): GuidanceStep | null {
  if (!countyInfo) return null;
  const { filingMethod } = countyInfo;
  if (filingMethod.online) {
    return {
      label: "File online",
      detail: `${countyInfo.cad} accepts online protest filing.${filingMethod.online.notes ? ` ${filingMethod.online.notes}` : ""}`,
      action: { label: "Open the county's filing portal", anchor: filingMethod.online.url },
    };
  }
  const mailOrInPerson = filingMethod.mail ?? filingMethod.inPerson;
  if (mailOrInPerson) {
    return {
      label: "Mail or deliver your Notice of Protest",
      detail: `${countyInfo.cad}'s real filing address: ${mailOrInPerson.address}${mailOrInPerson.notes ? ` — ${mailOrInPerson.notes}` : ""}`,
    };
  }
  return null;
}

export function getCaseGuidance(
  property: PropertyRecord,
  protest: ProtestRecord,
  evidenceDocumentCount: number | undefined,
  countyInfo: CountyProtestInfo | null,
  // Real timestamp from protest_form_submissions.signed_at (see
  // getSubmission() in protest-form-submissions.ts) — whether the customer
  // has actually signed their Notice of Protest in-app. Signing is NOT the
  // same as filing: this app has no e-filing integration with any county,
  // so it can never truthfully claim a protest is "filed" the moment it's
  // signed — only the customer, by actually delivering it, knows that. A
  // signed-but-undelivered case stays at the "prepare_file" stage with
  // different copy, rather than jumping to "filed" on its own say-so.
  noticeSignedAt?: string | null,
): CaseGuidance {
  const stage = STAGE_BY_STATUS[protest.status];
  const stageLabel = STAGE_LABEL[stage];
  const nextSteps: GuidanceStep[] = [];
  let summary: string;

  switch (stage) {
    case "prepare_file": {
      const deadline = property.protestDeadline;
      const hasRealDeadline = deadline != null && isFutureDate(deadline);
      if (noticeSignedAt) {
        summary =
          "You've signed your Notice of Protest. Signing it here doesn't file it with the county — you still need to deliver it (online, by mail, or in person), then confirm below once you have.";
        nextSteps.push({
          label: "Deliver your signed Notice of Protest, then confirm",
          detail:
            "Signing in this app only prepares the document — delivering it to your county is still on you.",
          action: { label: "Go to Documents", anchor: "case-documents" },
        });
        const methodStep = filingMethodStep(countyInfo);
        if (methodStep) nextSteps.push(methodStep);
      } else {
        summary = hasRealDeadline
          ? `Your protest deadline is ${formatDate(deadline!)}. Review your case, gather evidence, and file your Notice of Protest before then.`
          : "Review your case, gather evidence, and file your Notice of Protest when you're ready.";
        if (hasRealDeadline) {
          nextSteps.push({
            label: `File by ${formatDate(deadline!)}`,
            detail: "Review and sign your Notice of Protest (Form 50-132) below.",
            action: { label: "Review Notice of Protest", anchor: "case-documents" },
          });
        } else {
          nextSteps.push({
            label: "Review and sign your Notice of Protest",
            detail: "Form 50-132, pre-filled from your case's real data.",
            action: { label: "Review Notice of Protest", anchor: "case-documents" },
          });
        }
        nextSteps.push(...evidenceSteps(evidenceDocumentCount));
        const methodStep = filingMethodStep(countyInfo);
        if (methodStep) nextSteps.push(methodStep);
      }
      break;
    }
    case "filed": {
      summary =
        protest.status === "under_review"
          ? `${property.cad ?? "Your county"} is reviewing your filed protest. You may receive a settlement offer or a hearing date next.`
          : "Your Notice of Protest has been filed. The county will review it next — you may receive a settlement offer or a hearing date.";
      // Real notices only get read once the case has actually been filed —
      // before that there's nothing from the county to upload yet. Once a
      // real hearing date is confirmed from one (see HearingNoticeSection
      // in CaseDetailModal.tsx), the case advances past this stage and this
      // step stops showing on its own.
      nextSteps.push({
        label: "Upload the hearing notice or other notice received from the county",
        detail:
          "AI reads it, checks it against your case, and gets a real hearing date onto your calendar.",
        action: { label: "Go to Hearing Notice", anchor: "case-hearing-notice" },
      });
      nextSteps.push(...evidenceSteps(evidenceDocumentCount));
      if (countyInfo?.informalReview) {
        nextSteps.push({
          label: "Request an informal review",
          detail: countyInfo.informalReview.howToRequest,
        });
      }
      break;
    }
    case "informal_review": {
      const offer = protest.settlementOfferValue;
      summary =
        offer != null
          ? `${property.cad ?? "The county"} has offered to settle at ${formatCurrency(offer)}. Review it and decide whether to accept or continue to a formal hearing.`
          : "You're in informal review with the county. Review any offer you receive and decide whether to accept it or continue to a formal hearing.";
      nextSteps.push({
        label: "Review your settlement offer",
        detail: "Accept it to close your case, or continue toward a formal hearing.",
        action: { label: "Go to Case Progress", anchor: "case-progress" },
      });
      break;
    }
    case "hearing": {
      const date = protest.hearingDate;
      summary = date
        ? `Your formal ARB hearing is scheduled for ${formatDate(date)}. Prepare your evidence and know what to expect.`
        : "Your case is moving toward a formal ARB hearing. Prepare your evidence and know what to expect.";
      nextSteps.push(...evidenceSteps(evidenceDocumentCount));
      if (countyInfo?.arbContact) {
        const { phone, email } = countyInfo.arbContact;
        if (phone || email) {
          nextSteps.push({
            label: "Contact the Appraisal Review Board",
            detail: `${countyInfo.cad}'s ARB office${phone ? ` — ${phone}` : ""}${email ? ` — ${email}` : ""}`,
          });
        }
      }
      break;
    }
    case "decision": {
      summary = protest.arbDecision
        ? `The ARB's decision was recorded as "${protest.arbDecision}". Decide whether to accept the result, appeal to district court, or request binding arbitration.`
        : "Your hearing has taken place. Record the ARB's decision to see your options.";
      nextSteps.push({
        label: protest.arbDecision ? "Choose your next step" : "Record the ARB's decision",
        detail: protest.arbDecision
          ? "Accept, appeal, or request binding arbitration."
          : "Once recorded, you'll see your real options for accepting or escalating.",
        action: { label: "Go to Case Progress", anchor: "case-progress" },
      });
      break;
    }
    case "escalation": {
      summary =
        protest.escalationPath === "arbitration"
          ? "You've requested binding arbitration. This is handled directly with the Texas Comptroller's office."
          : "You've filed a district court appeal. This proceeds outside CorvusPT — an attorney typically represents you from here.";
      nextSteps.push({
        label: "Track your escalation",
        detail: "See the real resources and links for this path.",
        action: { label: "Go to Case Progress", anchor: "case-progress" },
      });
      break;
    }
    case "resolved": {
      summary =
        protest.finalValue != null
          ? `This case is resolved. Final value: ${formatCurrency(protest.finalValue)}.`
          : "This case is resolved.";
      break;
    }
  }

  return { stage, stageLabel, summary, nextSteps, countyInfo };
}
