/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AiReportRouteImport } from './routes/ai-report'
import { Route as BppRenditionRouteImport } from './routes/bpp-rendition'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentReviewRouteImport } from './routes/document-review'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PropertyProtestRouteImport } from './routes/property-protest'
import { Route as PropertyTaxManagementRouteImport } from './routes/property-tax-management'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TaxPaymentRouteImport } from './routes/tax-payment'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout.index'
import { Route as DashboardLayoutBillingRouteImport } from './routes/dashboard/_layout.billing'
import { Route as DashboardLayoutBppAccountsRouteImport } from './routes/dashboard/_layout.bpp-accounts'
import { Route as DashboardLayoutDeadlinesRouteImport } from './routes/dashboard/_layout.deadlines'
import { Route as DashboardLayoutDocumentsRouteImport } from './routes/dashboard/_layout.documents'
import { Route as DashboardLayoutPropertiesRouteImport } from './routes/dashboard/_layout.properties'
import { Route as DashboardLayoutSettingsRouteImport } from './routes/dashboard/_layout.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReportRoute = AiReportRouteImport.update({
  id: '/ai-report',
  path: '/ai-report',
  getParentRoute: () => rootRouteImport,
} as any)
const BppRenditionRoute = BppRenditionRouteImport.update({
  id: '/bpp-rendition',
  path: '/bpp-rendition',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentReviewRoute = DocumentReviewRouteImport.update({
  id: '/document-review',
  path: '/document-review',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyProtestRoute = PropertyProtestRouteImport.update({
  id: '/property-protest',
  path: '/property-protest',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyTaxManagementRoute = PropertyTaxManagementRouteImport.update({
  id: '/property-tax-management',
  path: '/property-tax-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxPaymentRoute = TaxPaymentRouteImport.update({
  id: '/tax-payment',
  path: '/tax-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutBillingRoute = DashboardLayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutBppAccountsRoute =
  DashboardLayoutBppAccountsRouteImport.update({
    id: '/bpp-accounts',
    path: '/bpp-accounts',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDeadlinesRoute =
  DashboardLayoutDeadlinesRouteImport.update({
    id: '/deadlines',
    path: '/deadlines',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDocumentsRoute =
  DashboardLayoutDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutPropertiesRoute =
  DashboardLayoutPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsRoute = DashboardLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-report': typeof AiReportRoute
  '/bpp-rendition': typeof BppRenditionRoute
  '/contact': typeof ContactRoute
  '/document-review': typeof DocumentReviewRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/property-protest': typeof PropertyProtestRoute
  '/property-tax-management': typeof PropertyTaxManagementRoute
  '/sign-in': typeof SignInRoute
  '/tax-payment': typeof TaxPaymentRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/billing': typeof DashboardLayoutBillingRoute
  '/dashboard/bpp-accounts': typeof DashboardLayoutBppAccountsRoute
  '/dashboard/deadlines': typeof DashboardLayoutDeadlinesRoute
  '/dashboard/documents': typeof DashboardLayoutDocumentsRoute
  '/dashboard/properties': typeof DashboardLayoutPropertiesRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-report': typeof AiReportRoute
  '/bpp-rendition': typeof BppRenditionRoute
  '/contact': typeof ContactRoute
  '/document-review': typeof DocumentReviewRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/property-protest': typeof PropertyProtestRoute
  '/property-tax-management': typeof PropertyTaxManagementRoute
  '/sign-in': typeof SignInRoute
  '/tax-payment': typeof TaxPaymentRoute
  '/dashboard/billing': typeof DashboardLayoutBillingRoute
  '/dashboard/bpp-accounts': typeof DashboardLayoutBppAccountsRoute
  '/dashboard/deadlines': typeof DashboardLayoutDeadlinesRoute
  '/dashboard/documents': typeof DashboardLayoutDocumentsRoute
  '/dashboard/properties': typeof DashboardLayoutPropertiesRoute
  '/dashboard/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/ai-report': typeof AiReportRoute
  '/bpp-rendition': typeof BppRenditionRoute
  '/contact': typeof ContactRoute
  '/document-review': typeof DocumentReviewRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/property-protest': typeof PropertyProtestRoute
  '/property-tax-management': typeof PropertyTaxManagementRoute
  '/sign-in': typeof SignInRoute
  '/tax-payment': typeof TaxPaymentRoute
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/billing': typeof DashboardLayoutBillingRoute
  '/dashboard/_layout/bpp-accounts': typeof DashboardLayoutBppAccountsRoute
  '/dashboard/_layout/deadlines': typeof DashboardLayoutDeadlinesRoute
  '/dashboard/_layout/documents': typeof DashboardLayoutDocumentsRoute
  '/dashboard/_layout/properties': typeof DashboardLayoutPropertiesRoute
  '/dashboard/_layout/settings': typeof DashboardLayoutSettingsRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ai-report'
    | '/bpp-rendition'
    | '/contact'
    | '/document-review'
    | '/how-it-works'
    | '/intake'
    | '/pricing'
    | '/property-protest'
    | '/property-tax-management'
    | '/sign-in'
    | '/tax-payment'
    | '/dashboard'
    | '/dashboard/billing'
    | '/dashboard/bpp-accounts'
    | '/dashboard/deadlines'
    | '/dashboard/documents'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ai-report'
    | '/bpp-rendition'
    | '/contact'
    | '/document-review'
    | '/how-it-works'
    | '/intake'
    | '/pricing'
    | '/property-protest'
    | '/property-tax-management'
    | '/sign-in'
    | '/tax-payment'
    | '/dashboard/billing'
    | '/dashboard/bpp-accounts'
    | '/dashboard/deadlines'
    | '/dashboard/documents'
    | '/dashboard/properties'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/ai-report'
    | '/bpp-rendition'
    | '/contact'
    | '/document-review'
    | '/how-it-works'
    | '/intake'
    | '/pricing'
    | '/property-protest'
    | '/property-tax-management'
    | '/sign-in'
    | '/tax-payment'
    | '/dashboard/_layout'
    | '/dashboard/_layout/billing'
    | '/dashboard/_layout/bpp-accounts'
    | '/dashboard/_layout/deadlines'
    | '/dashboard/_layout/documents'
    | '/dashboard/_layout/properties'
    | '/dashboard/_layout/settings'
    | '/dashboard/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AiReportRoute: typeof AiReportRoute
  BppRenditionRoute: typeof BppRenditionRoute
  ContactRoute: typeof ContactRoute
  DocumentReviewRoute: typeof DocumentReviewRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntakeRoute: typeof IntakeRoute
  PricingRoute: typeof PricingRoute
  PropertyProtestRoute: typeof PropertyProtestRoute
  PropertyTaxManagementRoute: typeof PropertyTaxManagementRoute
  SignInRoute: typeof SignInRoute
  TaxPaymentRoute: typeof TaxPaymentRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-report': {
      id: '/ai-report'
      path: '/ai-report'
      fullPath: '/ai-report'
      preLoaderRoute: typeof AiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpp-rendition': {
      id: '/bpp-rendition'
      path: '/bpp-rendition'
      fullPath: '/bpp-rendition'
      preLoaderRoute: typeof BppRenditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-review': {
      id: '/document-review'
      path: '/document-review'
      fullPath: '/document-review'
      preLoaderRoute: typeof DocumentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-protest': {
      id: '/property-protest'
      path: '/property-protest'
      fullPath: '/property-protest'
      preLoaderRoute: typeof PropertyProtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-tax-management': {
      id: '/property-tax-management'
      path: '/property-tax-management'
      fullPath: '/property-tax-management'
      preLoaderRoute: typeof PropertyTaxManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-payment': {
      id: '/tax-payment'
      path: '/tax-payment'
      fullPath: '/tax-payment'
      preLoaderRoute: typeof TaxPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/billing': {
      id: '/dashboard/_layout/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardLayoutBillingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/bpp-accounts': {
      id: '/dashboard/_layout/bpp-accounts'
      path: '/bpp-accounts'
      fullPath: '/dashboard/bpp-accounts'
      preLoaderRoute: typeof DashboardLayoutBppAccountsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/deadlines': {
      id: '/dashboard/_layout/deadlines'
      path: '/deadlines'
      fullPath: '/dashboard/deadlines'
      preLoaderRoute: typeof DashboardLayoutDeadlinesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/documents': {
      id: '/dashboard/_layout/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardLayoutDocumentsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/properties': {
      id: '/dashboard/_layout/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardLayoutPropertiesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings': {
      id: '/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutBillingRoute: typeof DashboardLayoutBillingRoute
  DashboardLayoutBppAccountsRoute: typeof DashboardLayoutBppAccountsRoute
  DashboardLayoutDeadlinesRoute: typeof DashboardLayoutDeadlinesRoute
  DashboardLayoutDocumentsRoute: typeof DashboardLayoutDocumentsRoute
  DashboardLayoutPropertiesRoute: typeof DashboardLayoutPropertiesRoute
  DashboardLayoutSettingsRoute: typeof DashboardLayoutSettingsRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutBillingRoute: DashboardLayoutBillingRoute,
  DashboardLayoutBppAccountsRoute: DashboardLayoutBppAccountsRoute,
  DashboardLayoutDeadlinesRoute: DashboardLayoutDeadlinesRoute,
  DashboardLayoutDocumentsRoute: DashboardLayoutDocumentsRoute,
  DashboardLayoutPropertiesRoute: DashboardLayoutPropertiesRoute,
  DashboardLayoutSettingsRoute: DashboardLayoutSettingsRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AiReportRoute: AiReportRoute,
  BppRenditionRoute: BppRenditionRoute,
  ContactRoute: ContactRoute,
  DocumentReviewRoute: DocumentReviewRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntakeRoute: IntakeRoute,
  PricingRoute: PricingRoute,
  PropertyProtestRoute: PropertyProtestRoute,
  PropertyTaxManagementRoute: PropertyTaxManagementRoute,
  SignInRoute: SignInRoute,
  TaxPaymentRoute: TaxPaymentRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
