/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiReportRouteImport } from './routes/ai-report'
import { Route as BppRenditionRouteImport } from './routes/bpp-rendition'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentReviewRouteImport } from './routes/document-review'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PropertyProtestRouteImport } from './routes/property-protest'
import { Route as PropertyTaxManagementRouteImport } from './routes/property-tax-management'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TaxPaymentRouteImport } from './routes/tax-payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReportRoute = AiReportRouteImport.update({
  id: '/ai-report',
  path: '/ai-report',
  getParentRoute: () => rootRouteImport,
} as any)
const BppRenditionRoute = BppRenditionRouteImport.update({
  id: '/bpp-rendition',
  path: '/bpp-rendition',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentReviewRoute = DocumentReviewRouteImport.update({
  id: '/document-review',
  path: '/document-review',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyProtestRoute = PropertyProtestRouteImport.update({
  id: '/property-protest',
  path: '/property-protest',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyTaxManagementRoute = PropertyTaxManagementRouteImport.update({
  id: '/property-tax-management',
  path: '/property-tax-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxPaymentRoute = TaxPaymentRouteImport.update({
  id: '/tax-payment',
  path: '/tax-payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-report': typeof AiReportRoute
  '/bpp-rendition': typeof BppRenditionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/document-review': typeof DocumentReviewRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/property-protest': typeof PropertyProtestRoute
  '/property-tax-management': typeof PropertyTaxManagementRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-payment': typeof TaxPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-report': typeof AiReportRoute
  '/bpp-rendition': typeof BppRenditionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/document-review': typeof DocumentReviewRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/property-protest': typeof PropertyProtestRoute
  '/property-tax-management': typeof PropertyTaxManagementRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-payment': typeof TaxPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-report': typeof AiReportRoute
  '/bpp-rendition': typeof BppRenditionRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/document-review': typeof DocumentReviewRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/property-protest': typeof PropertyProtestRoute
  '/property-tax-management': typeof PropertyTaxManagementRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-payment': typeof TaxPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-report'
    | '/bpp-rendition'
    | '/contact'
    | '/dashboard'
    | '/document-review'
    | '/how-it-works'
    | '/intake'
    | '/pricing'
    | '/property-protest'
    | '/property-tax-management'
    | '/sign-in'
    | '/sitemap.xml'
    | '/tax-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-report'
    | '/bpp-rendition'
    | '/contact'
    | '/dashboard'
    | '/document-review'
    | '/how-it-works'
    | '/intake'
    | '/pricing'
    | '/property-protest'
    | '/property-tax-management'
    | '/sign-in'
    | '/sitemap.xml'
    | '/tax-payment'
  id:
    | '__root__'
    | '/'
    | '/ai-report'
    | '/bpp-rendition'
    | '/contact'
    | '/dashboard'
    | '/document-review'
    | '/how-it-works'
    | '/intake'
    | '/pricing'
    | '/property-protest'
    | '/property-tax-management'
    | '/sign-in'
    | '/sitemap.xml'
    | '/tax-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReportRoute: typeof AiReportRoute
  BppRenditionRoute: typeof BppRenditionRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DocumentReviewRoute: typeof DocumentReviewRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntakeRoute: typeof IntakeRoute
  PricingRoute: typeof PricingRoute
  PropertyProtestRoute: typeof PropertyProtestRoute
  PropertyTaxManagementRoute: typeof PropertyTaxManagementRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxPaymentRoute: typeof TaxPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-report': {
      id: '/ai-report'
      path: '/ai-report'
      fullPath: '/ai-report'
      preLoaderRoute: typeof AiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpp-rendition': {
      id: '/bpp-rendition'
      path: '/bpp-rendition'
      fullPath: '/bpp-rendition'
      preLoaderRoute: typeof BppRenditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-review': {
      id: '/document-review'
      path: '/document-review'
      fullPath: '/document-review'
      preLoaderRoute: typeof DocumentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-protest': {
      id: '/property-protest'
      path: '/property-protest'
      fullPath: '/property-protest'
      preLoaderRoute: typeof PropertyProtestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-tax-management': {
      id: '/property-tax-management'
      path: '/property-tax-management'
      fullPath: '/property-tax-management'
      preLoaderRoute: typeof PropertyTaxManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-payment': {
      id: '/tax-payment'
      path: '/tax-payment'
      fullPath: '/tax-payment'
      preLoaderRoute: typeof TaxPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReportRoute: AiReportRoute,
  BppRenditionRoute: BppRenditionRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DocumentReviewRoute: DocumentReviewRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntakeRoute: IntakeRoute,
  PricingRoute: PricingRoute,
  PropertyProtestRoute: PropertyProtestRoute,
  PropertyTaxManagementRoute: PropertyTaxManagementRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxPaymentRoute: TaxPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
